package com.example.proyectoappgym.entity.realizationexercises

enum class Muscles(val nameMuscle: String, val groupMuscles: GroupMuscles) {
    UPPER_PECTORALS("Upper pectorals", GroupMuscles.PUSH_UP),
    PECTORALS("Pectorals", GroupMuscles.PUSH_UP),
    DELTOIDS("Deltoids", GroupMuscles.PUSH_UP),
    MIDDLE_DELTOID("Middle deltoid", GroupMuscles.PUSH_UP),
    FRONT_DELTOID("Front deltoid", GroupMuscles.PUSH_UP),
    POSTERIOR_DELTOID("Posterior deltoid", GroupMuscles.PUSH_UP),
    BRACHIAL("Brachialis", GroupMuscles.PUSH_UP),
    BRACHIORADIALIS("Brachioradialis", GroupMuscles.PUSH_UP),
    INFRASPINATUS("Infraspinatus", GroupMuscles.PUSH_UP),
    TERES_MAJOR("Teres major", GroupMuscles.PULL_UP),
    TERES_MINOR("Teres minor", GroupMuscles.PULL_UP),
    TRAPEZIUS("Trapezius", GroupMuscles.PULL_UP),
    LATISSIMUS_DORSI("Latissimus dorsi", GroupMuscles.PULL_UP),
    TRICEPS("Triceps", GroupMuscles.PUSH_UP),
    QUADRICEPS("Quadriceps", GroupMuscles.LEGS),
    GLUTEUS("Gluteus", GroupMuscles.LEGS),
    HAMSTRINGS("Hamstrings", GroupMuscles.LEGS),
    CALVES("Calves", GroupMuscles.LEGS),
    ADDUCTORS("Adductors", GroupMuscles.LEGS),
    LOWER_BACK("Lower back", GroupMuscles.PULL_UP),
    BICEPS("Biceps", GroupMuscles.PULL_UP),
    ABS("Abs", GroupMuscles.CORE),
    LOWER_ABS("Lower abs", GroupMuscles.CORE),
    MIDDLE_ABS("Middle abs", GroupMuscles.CORE),
    UPPER_ABS("Upper abs", GroupMuscles.CORE),
    OBLIQUES("Obliques", GroupMuscles.CORE),
    RHOMBOIDS("Rhomboids", GroupMuscles.PULL_UP),
    ILIOPSOAS("Iliopsoas", GroupMuscles.LEGS);
}